package notification;

import enums.NotificationType;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Represents a single admin notification/alert in the system.
 *
 * Generated by:
 *   - LoginAttemptTracker (FAILED_LOGIN_KNOWN, UNKNOWN_ID_ALERT)
 *   - RegistrationRequest (REG_REQUEST)
 *   - PasswordResetRequest (PASSWORD_RESET)
 *   - PaymentEngine (PAYMENT_REQUEST)
 *
 * Admin sees all notifications in NotificationCenter dashboard.
 */
public class Notification {

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    private static int idCounter = 1;

    // ─── Fields ───────────────────────────────────────────────
    private final int              notifId;
    private final NotificationType type;
    private final String           message;
    private final String           relatedEmail;
    private final String           timestamp;
    private boolean                isRead;

    // ─── Constructor ──────────────────────────────────────────
    public Notification(NotificationType type, String message, String relatedEmail) {
        if (type == null)
            throw new IllegalArgumentException("Notification type cannot be null.");
        if (message == null || message.trim().isEmpty())
            throw new IllegalArgumentException("Notification message cannot be empty.");

        this.notifId      = idCounter++;
        this.type         = type;
        this.message      = message.trim();
        this.relatedEmail = (relatedEmail != null) ? relatedEmail.trim() : "SYSTEM";
        this.timestamp    = LocalDateTime.now().format(FORMATTER);
        this.isRead       = false;
    }

    // ─── Actions ──────────────────────────────────────────────

    /** Mark this notification as read by Admin. */
    public void markAsRead() {
        this.isRead = true;
    }

    // ─── Display ──────────────────────────────────────────────

    /**
     * Get a formatted display string for Admin Dashboard.
     */
    public String getDisplayString() {
        return String.format(
            "[%s] [%s] %s\n         → Related: %s | Time: %s",
            isRead ? "✓ READ  " : "● UNREAD",
            type, message, relatedEmail, timestamp
        );
    }

    // ─── Getters ──────────────────────────────────────────────
    public int              getNotifId()      { return notifId; }
    public NotificationType getType()         { return type; }
    public String           getMessage()      { return message; }
    public String           getRelatedEmail() { return relatedEmail; }
    public String           getTimestamp()    { return timestamp; }
    public boolean          isRead()          { return isRead; }

    @Override
    public String toString() {
        return String.format("[%s][%s] %s — %s",
            isRead ? "READ" : "UNREAD", type, message, timestamp);
    }
}
